server:
  port: 8081

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Jibinjames158*
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: This is the value from application.properties !!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Jibinjames158*
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: This is the value from application.properties !!

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Jibinjames158*
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: This is the value from application.properties !!

